name: Build

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python
        run: python -m pip install --upgrade pip

#      - name: Install dependencies
#        run: pip install -r requirements.txt

      - name: Run Python
        run: python main.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
